In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [3]:
inputs.shape

torch.Size([6, 3])

In [2]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [4]:
attn_scores_2 = torch.empty(inputs.shape[0])
for idx , val in enumerate(inputs):
    attn_scores_2[idx] = torch.dot(val,input_query)
print(attn_scores_2)
    

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [5]:
attn_scores_temp = attn_scores_2/attn_scores_2.sum()
print("Normalized weights:", attn_scores_temp)
print(attn_scores_temp.sum())

Normalized weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


In [8]:
attn_scores_final = torch.softmax(attn_scores_2,dim =0)

In [7]:
input_query.shape

torch.Size([3])

In [9]:
context_vec = torch.zeros(input_query.shape)
for i, val in enumerate(inputs):
    context_vec += attn_scores_final[i]*inputs[i]

print(context_vec)

tensor([0.4419, 0.6515, 0.5683])
